const AdminConfig = {
    navbar: {
        button_1: 'HOME',
        button_2: 'PLAYERS',
        button_3: 'WAGONS',
        button_4: 'HORSES',
        button_5: 'TICKETS'
    },
    home: { 
        'announce': { icon: 'fas fa-bullhorn', label: 'ANNOUNCE', enabled: true }, 
        'noclip': { icon: 'fa-thin fa-snowflake', label: 'NOCLIP', enabled: true }, 
        'waypoint': { icon: 'fas fa-dollar-sign', label: 'WAYPOINT TP', enabled: true },
        'tpcoords': { icon: 'fas fa-coins', label: 'COORDS TP', enabled: true },
        'reviveall': { icon: 'fas fa-shield-alt', label: 'REVIVE ALL', enabled: true }, 
        'healall': { icon: 'fas fa-plus-circle', label: 'HEAL ALL', enabled: true },
        'kill': { icon: 'fas fa-skull-crossbones', label: 'KILL', enabled: true },   
        'adminstash': { icon: 'fas fa-map-marker-alt', label: 'ADMIN STASH', enabled: true },
        'wagonfix': { icon: 'fas fa-briefcase', label: 'WAGON FIX', enabled: true },
        'horserevive': { icon: 'fas fa-horse   ', label: 'HORSE REVIVE', enabled: true },
        'horseStimulant': { icon: 'fas fa-horse   ', label: 'HORSE STIMULANT', enabled: true }, 
        'horseBrush': { icon: 'fas fa-horse   ', label: 'HORSE BRUSH', enabled: true }, 
        'entitydelete': { icon: 'fa-solid fa-xmark', label: 'DELETE ENTITY', enabled: true }, 
        'clearzone': { icon: 'fas fa-thermometer-half', label: 'CLEAR ZONE', enabled: true },
        'playersblips': { icon: 'fas fa-handcuffs', label: 'PLAYERS BLIPS', enabled: true },
        'godmod': { icon: 'fas fa-paper-plane', label: 'GOD MOD', enabled: true }, 
        'invisible': { icon: 'fas fa-user-secret', label: 'INVISIBLE', enabled: true },
        'showplayertags': { icon: 'fas fa-user-tag', label: 'SHOW PLAYER TAGS', enabled: true },
        'vector2': { icon: 'fa-solid fa-location-dot', label: 'VECTOR 2', enabled: true },
        'vector3': { icon: 'fa-solid fa-location-dot', label: 'VECTOR 3', enabled: true },
        'vector4': { icon: 'fa-solid fa-location-dot', label: 'VECTOR 4', enabled: true },
        'showcoords': { icon: 'fa-regular fa-map-location-dot', label: 'SHOW COORDS', enabled: true },
        'targetobject': { icon: 'fas fa-user-shield', label: 'TARGET OBJECT', enabled: true },  
        'GiftMoney': { icon: 'fas fa-money-bill', label: 'GIFT MONEY', enabled: true }, 
        'GiftGold': { icon: 'fas fa-gem', label: 'GIFT GOLD', enabled: true }, 
        'infiniteammo': { icon: 'fa-solid fa-infinity', label: 'INFINITE AMMO', enabled: true },
        'goback': { icon: 'fas fa-undo', label: 'GO BACK', enabled: true },
        'fullcore': { icon: 'fas fa-heart-pulse', label: 'FULL CORES', enabled: true },
        'removeitems': { icon: 'fas fa-trash-alt', label: 'REMOVE ITEMS', enabled: true },    
        'removeweapons': { icon: 'fas fa-trash-alt', label: 'REMOVE WEAPONS', enabled: true },    
        'giveItems': { icon: 'fas fa-infinity', label: 'GIVE ITEMS', enabled: true },        
        'giveWeapons': { icon: 'fas fa-infinity', label: 'GIVE WEAPONS', enabled: true },
    },
    players: { 
        'spectate': { icon: 'fas fa-eye', label: 'SPECTATE', enabled: true },
        'permissions': { icon: 'fas fa-user-cog', label: 'PERMISSIONS', enabled: true }, 
        'show-inventory': { icon: 'fas fa-box', label: 'SHOW INVENTORY', enabled: true },
        'copy-vector2': { icon: 'fas fa-clone', label: 'VECTOR 2', enabled: true },
        'copy-vector3': { icon: 'fas fa-clone', label: 'VECTOR 3', enabled: true },
        'copy-vector4': { icon: 'fas fa-clone', label: 'VECTOR 4', enabled: true }, 
        'bring': { icon: 'fas fa-user-plus', label: 'BRING', enabled: true },
        'send-back': { icon: 'fas fa-undo', label: 'SEND BACK', enabled: true },
        'send-to-waypoint': { icon: 'fas fa-map-marker-alt', label: 'SEND TO WAYPOINT', enabled: true },
        'send-to-city': { icon: 'fas fa-city', label: 'SEND TO CITY', enabled: true }, 
        'out-group': { icon: 'fas fa-user-times', label: 'OUT GROUP', enabled: true },  
        'set-job': { icon: 'fas fa-briefcase', label: 'SET JOB', enabled: true }, 
        'set-currency': { icon: 'fas fa-dollar-sign', label: 'SET CURRENCY', enabled: true },
        'give-currency': { icon: 'fas fa-hand-holding-usd', label: 'GIVE CURRENCY', enabled: true },    
        'give-item': { icon: 'fas fa-gift', label: 'GIVE ITEM', enabled: true }, 
        'give-weapon': { icon: 'fas fa-gift', label: 'GIVE WEAPON', enabled: true },
        'player-notify': { icon: 'fas fa-bell', label: 'PLAYER NOTIFY', enabled: true }, 
        'fullcore': { icon: 'fas fa-heart-pulse', label: 'FULL CORES', enabled: true },
        'freeze': { icon: 'fas fa-snowflake', label: 'FREEZE', enabled: true },
        'unfreeze': { icon: 'fas fa-fire', label: 'UNFREEZE', enabled: true }, 
        'handcuff': { icon: 'fas fa-handcuffs', label: 'HANDCUFF', enabled: true },     
        'uncuff': { icon: 'fas fa-handcuffs', label: 'UNCUFF', enabled: true },
        'ragdoll': { icon: 'fas fa-user-injured', label: 'RAGDOLL', enabled: true },
        'remove-items': { icon: 'fas fa-trash-alt', label: 'REMOVE ITEMS', enabled: true },
        'remove-weapons': { icon: 'fas fa-ban', label: 'REMOVE WEAPONS', enabled: true },  
        'warn': { icon: 'fas fa-exclamation-triangle', label: 'WARN', enabled: true },
        'deletewarn': { icon: 'fas fa-check-circle', label: 'DELETE WARN', enabled: true },  
        'unban': { icon: 'fas fa-ban', label: 'UNBAN', enabled: true },
        'ban': { icon: 'fas fa-ban', label: 'BAN', enabled: true },
        'jail': { icon: 'fa-duotone fa-regular fa-hammer-war', label: 'JAIL', enabled: true },
        'unjail': { icon: 'fa-duotone fa-regular fa-hammer-war', label: 'UNJAIL', enabled: true },
        'kick': { icon: 'fas fa-user-times', label: 'KICK', enabled: true }, 
        'fire': { icon: 'fas fa-fire-alt', label: 'FIRE', enabled: true },
        'lightning': { icon: 'fas fa-bolt', label: 'LIGHTNING', enabled: true },
        'high-temp': { icon: 'fas fa-thermometer-full', label: 'HIGH TEMP', enabled: true },  
    },
    playerInfo: {
        money: {
            title: 'MONEY',
            subItems: [
                { key: 'player_money', title: 'Player Money' },
                { key: 'player_gold', title: 'Player Gold' }
            ]
        },
        job: {
            title: 'JOB',
            subItems: [
                { key: 'job_name', title: 'Job Name' },
                { key: 'job_grade', title: 'Job Grade' },
                { key: 'salary', title: 'Salary' }
            ]
        },
        account: {
            title: 'INFORMATIONS',
            subItems: [
                { key: 'steam', title: 'STEAM', AllowCopy: true },
                { key: 'steam_name', title: 'STEAM NAME', AllowCopy: true },
                { key: 'ic_name', title: 'IC NAME', AllowCopy: true },
                { key: 'group', title: 'GROUP' },
                { key: 'connected', title: 'CONNECTED' },
                { key: 'connected_ip', title: 'CONNECTED IP', AllowCopy: true },
                { key: 'rdr2_license', title: 'Rdr2', AllowCopy: true },
                { key: 'discord', title: 'DISCORD', AllowCopy: true },
                { key: 'coords', title: 'XYZ', AllowCopy: true }
            ]
        }
    },
    noclipHelp: {
        items: [
            { label: 'ForWard', key: 'W' },
            { label: 'BackWard', key: 'S' },
            { label: 'Left', key: 'A' },
            { label: 'Right', key: 'D' },
            { label: 'Up', key: 'E' },
            { label: 'Down', key: 'Q' },
            { label: 'Speed Up', key: 'Up Scroll' },
            { label: 'Speed Dawn', key: 'Dawn Scroll' },
            { label: 'Speed Reset', key: 'Click Scroll' }
        ]
    },
    buttons: {
        'announce': { label: 'SEND MESSAGE' },
        'tpcoords': { label: 'TELEPORT' },
        'sendgift': { label: 'SEND GIFT' }, 
        'notify': { label: 'SEND NOTIFY' },
        'set-currency': { label: 'SET CURRENCY' },
        'give-currency': { label: 'GIVE CURRENCY' },
        'give-item': { label: 'GIVE ITEM' },
        'deletewarn': { label: 'DELETE WARN' },
    },
    translations: {
        'permissions': 'PERMISSIONS',
        'copied': 'Copied!',
        'owner': 'owner',
        'user': 'user',
        'na': 'N/A',
        'home_permissions': 'HOME BUTTONS',
        'players_permissions': 'PLAYERS OPTIONS',
        'tpcoordsPlaceholder': 'Enter coordinates (x, y, z)...',
        'giftmoneyPlaceholder': 'Enter amount of money to gift...',
        'giftgoldPlaceholder': 'Enter amount of gold to gift...',
        'homeTitle': 'HOME',  
        'playersTitle': 'PLAYERS',
        'wagonsTitle': 'WAGONS',
        'horsesTitle': 'HORSES',
        'ticketsTitle': 'TICKETS',
        'permissionsHomeBtnTitle': 'HOME BUTTONS',
        'playersOptionsTitle': 'PLAYERS OPTIONS',
        'giveItemsTitle': 'GIVE ITEMS',
        'giveWeaponsTitle': 'GIVE WEAPONS',
        'giveItemsSearchPlaceholder': 'Search items...',
        'giveItemsAmountPlaceholder': 'Amount...',
        'giveWeaponsSearchPlaceholder': 'Search weapons...',
        'giveWeaponsAmountPlaceholder': 'Amount...',
        'wagonsSearchPlaceholder': 'Search wagons...',
        'horsesSearchPlaceholder': 'Search horses...',
        'notItemImage': 'No image',
        'giveItemBtn': 'GIVE',
        'spawnBtn': 'SPAWN',
        'jailDurationPlaceholder': 'Number of checkpoints...',
        'jailReasonPlaceholder': 'Jail Reason...',
        'jailPlayerBtn': 'JAIL PLAYER',
        'notifyPlaceholder': 'Message to send to player...',
    },
    Wagons: {
        ArmySupplyWagon: {name: 'Army Supply Wagon', image: 'wagons/wagonarmoured01x.PNG'},
        bountywagon01x: {name: 'Bounty Wagon', image: 'wagons/bountywagon01x.PNG'},
        buggy01: {name: 'Buggy 1', image: 'wagons/buggy01.PNG'},
        buggy02: {name: 'Buggy 2', image: 'wagons/buggy02.PNG'},
        buggy03: {name: 'Buggy 3', image: 'wagons/buggy03.PNG'},
        chuckwagon000x: {name: 'Chuck Wagon 0', image: 'wagons/chuckwagon000x.PNG'},
        chuckwagon002x: {name: 'Chuck Wagon 2', image: 'wagons/chuckwagon002x.PNG'},
        coach2: {name: 'Coach 2', image: 'wagons/coach2.PNG'},
        coach3: {name: 'Coach 3', image: 'wagons/coach3.PNG'},
        coach3_cutscene: {name: 'Coach 3 Cutscene', image: 'wagons/coach3_cutscene.PNG'},
        coach4: {name: 'Coach 4', image: 'wagons/coach4.PNG'},
        coach5: {name: 'Coach 5', image: 'wagons/coach5.PNG'},
        coach6: {name: 'Coach 6', image: 'wagons/coach6.PNG'},
        coal_wagon: {name: 'Coal Wagon', image: 'wagons/coal_wagon.PNG'},
        gatchuck: {name: 'Gatchuck', image: 'wagons/gatchuck.PNG'},
        gatchuck_2: {name: 'Gatchuck', image: 'wagons/gatchuck_2.PNG'},
        huntercart01: {name: 'Hunter Cart', image: 'wagons/huntercart01.PNG'},
        logwagon: {name: 'Log Wagon', image: 'wagons/logwagon.PNG'},
        oilWagon01x: {name: 'Oil Wagon', image: 'wagons/oilWagon01x.PNG'},
        oilWagon02x: {name: 'Oil Wagon', image: 'wagons/oilWagon02x.PNG'}, 
        policewagon01x: {name: 'Police Wagon', image: 'wagons/policewagon01x.PNG'},
        stagecoach001x: {name: 'Stagecoach', image: 'wagons/stagecoach001x.PNG'},
        stagecoach002x: {name: 'Stagecoach', image: 'wagons/stagecoach002x.PNG'},
        stagecoach003x: {name: 'Stagecoach', image: 'wagons/stagecoach003x.PNG'},
        stagecoach004x: {name: 'Stagecoach', image: 'wagons/stagecoach004x.PNG'},   
        stagecoach005x: {name: 'Stagecoach', image: 'wagons/stagecoach005x.PNG'},
        stagecoach006x: {name: 'Stagecoach', image: 'wagons/stagecoach006x.PNG'},
        supplywagon: {name: 'Supply Wagon', image: 'wagons/supplywagon.PNG'},
        utilliwag: {name: 'Utility Wagon', image: 'wagons/utilliwag.PNG'}, 
        wagon02x: {name: 'Wagon 2', image: 'wagons/wagon02x.PNG'},
        wagon03x: {name: 'Wagon 3', image: 'wagons/wagon03x.PNG'},
        wagon04x: {name: 'Wagon 4', image: 'wagons/wagon04x.PNG'},
        wagon05x: {name: 'Wagon 5', image: 'wagons/wagon05x.PNG'},
        wagon06x: {name: 'Wagon 6', image: 'wagons/wagon06x.PNG'},
        wagonarmoured01x: {name: 'Wagon Armoured', image: 'wagons/wagonarmoured01x.PNG'},
        wagonCircus01x: {name: 'Wagon Circus', image: 'wagons/wagonCircus01x.PNG'},
        wagondairy01x: {name: 'Wagon Dairy', image: 'wagons/wagondairy01x.PNG'},
        wagondoc01x: {name: 'Wagon Doc', image: 'wagons/wagondoc01x.PNG'},
        wagonPrison01x: {name: 'Wagon Prison', image: 'wagons/wagonPrison01x.PNG'},
        wagontraveller01x: {name: 'Wagon Traveller', image: 'wagons/wagontraveller01x.PNG'},
        wagonwork01x: {name: 'Wagon Work', image: 'wagons/wagonwork01x.PNG'},
        warwagon2: {name: 'Wagon War', image: 'wagons/warwagon2.PNG'},  
    },
    Horses: {
        A_C_Horse_Arabian_White: {name: 'Arabian White', image: 'horses/arabian_white.png'},
        A_C_Horse_Arabian_RoseGreyBay: {name: 'Arabian Rose Grey Bay', image: 'horses/arabian_rosegreybay.png'},
        A_C_Horse_Arabian_Black: {name: 'Arabian Black', image: 'horses/arabian_black.png'},
        A_C_Horse_Arabian_Grey: {name: 'Arabian Grey', image: 'horses/arabian_grey.png'},
        A_C_Horse_Arabian_WarpedBrindle_PC: {name: 'Arabian Warped Brindle', image: 'horses/arabian_WarpedBrindle.png'},
        A_C_Horse_Arabian_RedChestnut: {name: 'Arabian Red Chestnut', image: 'horses/arabian_RedChestnut.png'},   
        A_C_Horse_Ardennes_IronGreyRoan: {name: 'Ardennes Iron Grey Roan', image: 'horses/ardennes_irongrey.png'},  
        A_C_Horse_Ardennes_StrawberryRoan: {name: 'Ardennes Strawberry Roan', image: 'horses/ardennes_strawberryroan.png'},      
        A_C_Horse_Ardennes_BayRoan: {name: 'Ardennes Bay Roan', image: 'horses/ardennes_bayroan.png'},  
        A_C_Horse_MissouriFoxTrotter_AmberChampagne: {name: 'Missouri Fox Trotter Amber Champagne', image: 'horses/missouri_amber.png'},
        A_C_Horse_MissouriFoxTrotter_SableChampagne: {name: 'Missouri Fox Trotter Sable Champagne', image: 'horses/missouri_sable.png'},
        A_C_Horse_MissouriFoxTrotter_SilverDapplePinto: {name: 'Missouri Fox Trotter Silver Dapple Pinto', image: 'horses/missouri_silverpinto.png'}, 
        A_C_Horse_Turkoman_Gold: {name: 'Turkoman Gold', image: 'horses/turkoman_gold.png'},
        A_C_Horse_Turkoman_Silver: {name: 'Turkoman Silver', image: 'horses/turkoman_silver.png'},
        A_C_Horse_Turkoman_DarkBay: {name: 'Turkoman Dark Bay', image: 'horses/turkoman_dark.png'}, 
        A_C_Horse_Appaloosa_BlackSnowflake: {name: 'Appaloosa Black Snowflake', image: 'horses/appalosa_snowflake.png'},
        A_C_Horse_Appaloosa_BrownLeopard: {name: 'Appaloosa Brown Leopard', image: 'horses/appalosa_Brown.png'},
        A_C_Horse_Appaloosa_Leopard: {name: 'Appaloosa Leopard', image: 'horses/appalosa_leopard.png'},
        A_C_Horse_Appaloosa_FewSpotted_PC: {name: 'Appaloosa Few Spotted', image: 'horses/appalosa_few.png'},
        A_C_Horse_Appaloosa_Blanket: {name: 'Appaloosa Blanket', image: 'horses/appalosa_Blanket.png'},      
        A_C_Horse_Appaloosa_LeopardBlanket: {name: 'Appaloosa Leopard Blanket', image: 'horses/appalosa_leopardblanket.png'},  
        A_C_Horse_Mustang_GoldenDun: {name: 'Mustang Golden Dun', image: 'horses/mustang_goldendun.PNG.png'},
        A_C_Horse_Mustang_TigerStripedBay: {name: 'Mustang Tiger Striped Bay', image: 'horses/mustang_tigerstripedbay.PNG.png'},
        A_C_Horse_Mustang_GrulloDun: {name: 'Mustang Grullo Dun', image: 'horses/muistang_grullodun.PNG.png'},
        A_C_Horse_Mustang_WildBay: {name: 'Mustang Wild Bay', image: 'horses/mustang_wildbay.PNG.png'},     
        A_C_Horse_Thoroughbred_BlackChestnut: {name: 'Thoroughbred Black Chestnut', image: 'horses/Thoroughbred_black.PNG.png'},
        A_C_Horse_Thoroughbred_BloodBay: {name: 'Thoroughbred Blood Bay', image: 'horses/Thoroughbred_bloodbay.PNG.png'},
        A_C_Horse_Thoroughbred_Brindle: {name: 'Thoroughbred Brindle', image: 'horses/Thoroughbred_brindle.PNG.png'},
        A_C_Horse_Thoroughbred_ReverseDappleBlack: {name: 'Thoroughbred Reverse Dapple Black', image: 'horses/Thoroughbred_reverseblack.PNG.png'},
        A_C_Horse_Thoroughbred_DappleGrey: {name: 'Thoroughbred Dapple Grey', image: 'horses/Thoroughbred_dapplegrey.PNG.png'},  
        A_C_Horse_Andalusian_Perlino: {name: 'Andalusian Perlino', image: 'horses/andalusian_perlino.PNG.png'}, 
        A_C_Horse_Andalusian_RoseGray: {name: 'Andalusian Rose Gray', image: 'horses/andalusian_rosegrey.PNG.png'},
        A_C_Horse_Andalusian_DarkBay: {name: 'Andalusian Dark Bay', image: 'horses/andalusian_darkray.PNG.png'},  
        A_C_Horse_DutchWarmblood_ChocolateRoan: {name: 'Dutch Warmblood Chocolate Roan', image: 'horses/dutch_chocolateroan.PNG.png'},
        A_C_Horse_DutchWarmblood_SealBrown: {name: 'Dutch Warmblood Seal Brown', image: 'horses/dutch_sealbrown.PNG.png'},
        A_C_Horse_DutchWarmblood_SootyBuckskin: {name: 'Dutch Warmblood Sooty Buckskin', image: 'horses/dutch_sootybuckskin.PNG.png'},  
        A_C_Horse_AmericanPaint_Greyovero: {name: 'American Paint Grey Overo', image: 'horses/American_grey.PNG.png'},
        A_C_Horse_AmericanPaint_SplashedWhite: {name: 'American Paint Splashed White', image: 'horses/American_white.PNG.png'},
        A_C_Horse_AmericanPaint_Tobiano: {name: 'American Paint Tobiano', image: 'horses/American_torbino.PNG.png'},
        A_C_Horse_AmericanPaint_Overo: {name: 'American Paint Overo', image: 'horses/American_ovaro.PNG.png'},
        A_C_Horse_AmericanStandardbred_SilverTailBuckskin: {name: 'American Standardbred Silver Tail Buckskin', image: 'horses/American_silver.PNG.png'},
        A_C_Horse_AmericanStandardbred_PalominoDapple: {name: 'American Standardbred Palomino Dapple', image: 'horses/American_palomino.PNG.png'},      
        A_C_Horse_AmericanStandardbred_Black: {name: 'American Standardbred Black', image: 'horses/American_black.PNG.png'},   
        A_C_Horse_AmericanStandardbred_Buckskin: {name: 'American Standardbred Buckskin', image: 'horses/American_buckskin.PNG.png'},     
        A_C_Horse_KentuckySaddle_ButterMilkBuckskin_PC: {name: 'Kentucky Saddle Butter Milk Buckskin', image: 'horses/Kentucky_milk.PNG.png'},   
        A_C_Horse_KentuckySaddle_Black: {name: 'Kentucky Saddle Black', image: 'horses/Kentucky_black.PNG.png'},
        A_C_Horse_KentuckySaddle_ChestnutPinto: {name: 'Kentucky Saddle Chestnut Pinto', image: 'horses/Kentucky_pinto.PNG.png'},
        A_C_Horse_KentuckySaddle_Grey: {name: 'Kentucky Saddle Grey', image: 'horses/Kentucky_grey.PNG.png'},
        A_C_Horse_KentuckySaddle_SilverBay: {name: 'Kentucky Saddle Silver Bay', image: 'horses/Kentucky_silver.PNG.png'},   
        A_C_Horse_HungarianHalfbred_DarkDappleGrey: {name: 'Hungarian Dark Dapple Grey', image: 'horses/hungarian_dark.PNG.png'},
        A_C_Horse_HungarianHalfbred_LiverChestnut: {name: 'Hungarian Liver Chestnut', image: 'horses/hungarian_liver.PNG.png'},
        A_C_Horse_HungarianHalfbred_FlaxenChestnut: {name: 'Hungarian Flaxen Chestnut', image: 'horses/hungarian_flaxen.PNG.png'},
        A_C_Horse_HungarianHalfbred_PiebaldTobiano: {name: 'Hungarian Piebald Tobiano', image: 'horses/hungarian_piebald.PNG.png'}, 
        A_C_Horse_SuffolkPunch_RedChestnut: {name: 'Suffolk Punch Red Chestnut', image: 'horses/Suffolk_red.PNG.png'},
        A_C_Horse_SuffolkPunch_Sorrel: {name: 'Suffolk Punch Sorrel', image: 'horses/Suffolk_sorrel.PNG.png'}, 
        A_C_Horse_TennesseeWalker_FlaxenRoan: {name: 'Tennessee Walker Flaxen Roan', image: 'horses/Tennessee_flaxen.PNG.png'},
        A_C_Horse_TennesseeWalker_BlackRabicano: {name: 'Tennessee Walker Black Rabicano', image: 'horses/Tennessee_black.PNG.png'},
        A_C_Horse_TennesseeWalker_Chestnut: {name: 'Tennessee Walker Chestnut', image: 'horses/Tennessee_Chestnut.PNG.png'},
        A_C_Horse_TennesseeWalker_DappleBay: {name: 'Tennessee Walker Dapple Bay', image: 'horses/Tennessee_dapple.PNG.png'},
        A_C_Horse_TennesseeWalker_MahoganyBay: {name: 'Tennessee Walker Mahogany Bay', image: 'horses/Tennessee_Mahogany.PNG.png'},
        A_C_Horse_TennesseeWalker_RedRoan: {name: 'Tennessee Walker Red Roan', image: 'horses/Tennessee_red.PNG.png'},
        A_C_Horse_TennesseeWalker_GoldPalomino_PC: {name: 'Tennessee Walker Gold Palomino', image: 'horses/Tennessee_gold.PNG.png'}, 
        A_C_Horse_Shire_LightGrey: {name: 'Shire Light Grey', image: 'horses/Shire_light.PNG.png'},
        A_C_Horse_Shire_RavenBlack: {name: 'Shire Raven Black', image: 'horses/Shire_raven.PNG.png'},
        A_C_Horse_Shire_DarkBay: {name: 'Shire Dark Bay', image: 'horses/Shire_dark.PNG.png'}, 
        A_C_Horse_Belgian_BlondChestnut: {name: 'Belgian Blond Chestnut', image: 'horses/Belgian_blond.PNG.png'},
        A_C_Horse_Belgian_MealyChestnut: {name: 'Belgian Mealy Chestnut', image: 'horses/Belgian_mealy.PNG.png'},
        A_C_Horse_Morgan_Palomino: {name: 'Morgan Palomino', image: 'horses/morgan_palomino.PNG.png'},
        A_C_Horse_Morgan_Bay: {name: 'Morgan Bay', image: 'horses/morgan_bay.PNG.png'},
        A_C_Horse_Morgan_BayRoan: {name: 'Morgan Bay Roan', image: 'horses/morgan_bayroan.PNG.png'},
        A_C_Horse_Morgan_FlaxenChestnut: {name: 'Morgan Flaxen Chestnut', image: 'horses/morgan_flaxen.PNG.png'},
        A_C_Horse_Morgan_LiverChestnut_PC: {name: 'Morgan Liver Chestnut', image: 'horses/morgan_liver.PNG.png'},
        A_C_Horse_Gang_Dutch: {name: 'Gang Dutch', image: 'horses/horse_gang.PNG.png'},
        A_C_HorseMule_01: {name: 'Mule', image: 'horses/horse_mule.PNG.png'},
        A_C_HorseMulePainted_01: {name: 'Mule Painted', image: 'horses/horse_mule.PNG.png'},
        A_C_Donkey_01: {name: 'Donkey', image: 'horses/horse_donkey.PNG.png'},
        A_C_Horse_MP_Mangy_Backup: {name: 'Mangy Backup', image: 'horses/horse_mangy.PNG.png'}, 
    },
    Weapons: {
        'WEAPON_REPEATER_WINCHESTER': {name: 'Repeater Winchester'},
        'WEAPON_BOW': {name: 'Bow'},
        'WEAPON_LASSO_REINFORCED': {name: 'Lasso Reinforced'},
        'WEAPON_PISTOL_M1899': {name: 'Pistol M1899'},
        'WEAPON_MELEE_KNIFE_JAWBONE': {name: 'Knife Jawbone'},
        'WEAPON_THROWN_THROWING_KNIVES': {name: 'Throwing Knives'},
        'WEAPON_LASSO': {name: 'Lasso'},
        'WEAPON_KIT_CAMERA': {name: 'Camera'},
        'WEAPON_MELEE_TORCH': {name: 'Torch'},
        'WEAPON_MELEE_LANTERN': {name: 'Lantern'},
        'WEAPON_FISHINGROD': {name: 'Fishing Rod'},
        'WEAPON_MELEE_CLEAVER': {name: 'Cleaver'},
        'WEAPON_SHOTGUN_SAWEDOFF': {name: 'Shotgun Sawed Off'},
        'WEAPON_KIT_BINOCULARS': {name: 'Binoculars'},
        'WEAPON_PISTOL_SEMIAUTO': {name: 'Pistol Semi Auto'},
        'WEAPON_RIFLE_BOLTACTION': {name: 'Rifle Bolt Action'},
        'WEAPON_SHOTGUN_PUMP': {name: 'Shotgun Pump'},
        'WEAPON_REVOLVER_CATTLEMAN': {name: 'Revolver Cattleman'},
        'WEAPON_RIFLE_SPRINGFIELD': {name: 'Rifle Springfield'},
        'WEAPON_BOW_IMPROVED': {name: 'Bow Improved'},
        'WEAPON_MELEE_MACHETE_COLLECTOR': {name: 'Machete Collector'},
        'WEAPON_THROWN_DYNAMITE': {name: 'Dynamite'},
        'WEAPON_REVOLVER_CATTLEMAN_MEXICAN': {name: 'Revolver Cattleman Mexican'},
        'WEAPON_SNIPERRIFLE_ROLLINGBLOCK': {name: 'Sniper Rifle Rolling Block'},
        'WEAPON_THROWN_TOMAHAWK': {name: 'Tomahawk'},
        'WEAPON_SHOTGUN_SEMIAUTO': {name: 'Shotgun Semi Auto'},
        'WEAPON_REPEATER_HENRY': {name: 'Repeater Henry'},
        'WEAPON_PISTOL_VOLCANIC': {name: 'Pistol Volcanic'},
        'WEAPON_THROWN_TOMAHAWK_ANCIENT': {name: 'Tomahawk Ancient'},
        'WEAPON_MOONSHINEJUG_MP': {name: 'Moonshine Jug'},
        'WEAPON_SHOTGUN_REPEATING': {name: 'Shotgun Repeating'},
        'WEAPON_THROWN_MOLOTOV': {name: 'Molotov'},
        'WEAPON_SHOTGUN_DOUBLEBARREL': {name: 'Shotgun Double Barrel'},
        'WEAPON_REPEATER_EVANS': {name: 'Repeater Evans'},
        'WEAPON_REVOLVER_NAVY': {name: 'Revolver Navy'},
        'WEAPON_RIFLE_ELEPHANT': {name: 'Rifle Elephant'},
        'WEAPON_PISTOL_MAUSER': {name: 'Pistol Mauser'},
        'WEAPON_REVOLVER_SCHOFIELD': {name: 'Revolver Schofield'},
        'WEAPON_RIFLE_VARMINT': {name: 'Rifle Varmint'},
        'WEAPON_MELEE_KNIFE': {name: 'Knife'},
        'WEAPON_REVOLVER_LEMAT': {name: 'Revolver Lemat'},
        'WEAPON_KIT_METAL_DETECTOR': {name: 'Metal Detector'},
        'WEAPON_REVOLVER_DOUBLEACTION': {name: 'Revolver Double Action'},
        'WEAPON_THROWN_BOLAS': {name: 'Bolas'},
        'WEAPON_MELEE_HAMMER': {name: 'Hammer'},
        'WEAPON_MELEE_MACHETE_HORROR': {name: 'Machete Horror'},
        'WEAPON_MELEE_HATCHET': {name: 'Hatchet'},
        'WEAPON_MELEE_KNIFE_TRADER': {name: 'Knife Trader'},
        'WEAPON_REPEATER_CARBINE': {name: 'Repeater Carbine'},
        'WEAPON_REVOLVER_DOUBLEACTION_GAMBLER': {name: 'Revolver Double Action Gambler'},
        'WEAPON_SNIPERRIFLE_CARCANO': {name: 'Sniper Rifle Carcano'},
        'WEAPON_MELEE_MACHETE': {name: 'Machete'},
        'WEAPON_MELEE_HATCHET_HUNTER': {name: 'Hatchet Hunter'},
        'WEAPON_MELEE_DAVY_LANTERN': {name: 'Davy Lantern'},
        'WEAPON_KIT_BINOCULARS_IMPROVED': {name: 'Binoculars Improved'},
    }, 
    Citys: {
        'saintdenis': {name: 'Saint Denis', x: 2599.19, y: -1301.24, z: 52.82},
        'valentine': {name: 'Valentine', x: -312.47, y: 792.18, z: 118.43},
        'blackwater': {name: 'Blackwater', x: -810.05, y: -1237.47, z: 43.46},
        'rhodes': {name: 'Rhodes', x: 1276.12, y: -1302.26, z: 76.53},
        'strawberry': {name: 'Strawberry', x: -1769.76, y: -429.56, z: 155.66},
        'tumbleweed': {name: 'Tumbleweed', x: -5506.66, y: -2944.59, z: -1.89},
        'armadillo': {name: 'Armadillo', x: -3636.56, y: -2598.66, z: -13.62},
        'annesburg': {name: 'Annesburg', x: 2895.82, y: 1228.02, z: 44.57},
        'vanhorn': {name: 'Van Horn', x: 2975.34, y: 439.05, z: 50.32},
        'emeraldranch': {name: 'Emerald Ranch', x: 1381.12, y: -263.38, z: 72.06},
        'lagras': {name: 'Lagras', x: 2108.56, y: -619.64, z: 41.27},
        'colter': {name: 'Colter', x: -1368.51, y: 2390.49, z: 307.39},
        'wapiti': {name: 'Wapiti', x: 554.49, y: 2191.07, z: 244.38},
        'butchercreek': {name: 'Butcher Creek', x: 2497.64, y: 731.43, z: 64.91},
        'manzanitapost': {name: 'Manzanita Post', x: -1974.78, y: -1549.95, z: 114.36}
    }
};
